name: Update Organization Activity Graph

on:
  schedule:
    - cron: "0 0 * * *" # Автозапуск каждую ночь
  workflow_dispatch: # Кнопка ручного запуска

permissions:
  contents: write # Разрешение на пуш картинки

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Activity SVG
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Инициализируем директорию, куда запишется файл
      - name: Prepare Directory
        run: mkdir -p profile-3d-contrib

      # Генератор 3D-графика, который полностью поддерживает организации
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GRAPH_TOKEN }}

      # Чистый пуш созданного SVG-файла
      - name: Commit and Push Generated SVG
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add profile-3d-contrib/
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update organization activity graph"
          git push
